"""scope knowledge base names to workspace

Revision ID: 032ebe0c3b80
Revises: ea74637424be
Create Date: 2026-08-14 14:36:13.944450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032ebe0c3b80'
down_revision: Union[str, Sequence[str], None] = 'ea74637424be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('knowledge_bases_name_key'), 'knowledge_bases', type_='unique')
    op.create_unique_constraint('uq_knowledge_bases_workspace_name', 'knowledge_bases', ['workspace_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_knowledge_bases_workspace_name', 'knowledge_bases', type_='unique')
    op.create_unique_constraint(op.f('knowledge_bases_name_key'), 'knowledge_bases', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
