"""add workspace ownership to knowledge bases

Revision ID: 943aac58a233
Revises: ce0c7ed139a6
Create Date: 2026-08-11 13:13:31.188533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943aac58a233'
down_revision: Union[str, Sequence[str], None] = 'ce0c7ed139a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('workspace_id', sa.Uuid(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_knowledge_bases_workspace_id'), 'knowledge_bases', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bases_workspace_id'), table_name='knowledge_bases')
    op.drop_column('knowledge_bases', 'workspace_id')
    # ### end Alembic commands ###
